### ISSUE TITLE
seeding the database fails for review

### ISSUE THREAD

**Issue by ryan-whit** [Reyes-Jose/project-2#35]
Running `npm run seed` seeds the Restaurant data but not the Review data.

Current behavior:

```
rwhit@rwmac ~/Develop/ucb_bootcamp/project-2 (29-restaurant-views) $ npm run seed

> project-2-group-2@1.0.0 seed
> node seeds/seed.js

Executing (default): DROP TABLE IF EXISTS `review`;
Executing (default): DROP TABLE IF EXISTS `user`;
Executing (default): DROP TABLE IF EXISTS `restaurant`;
Executing (default): SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'restaurant' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='restreview_db' AND REFERENCED_TABLE_NAME IS NOT NULL;
Executing (default): SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'review' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='restreview_db' AND REFERENCED_TABLE_NAME IS NOT NULL;
Executing (default): SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'user' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='restreview_db' AND REFERENCED_TABLE_NAME IS NOT NULL;
Executing (default): DROP TABLE IF EXISTS `restaurant`;
Executing (default): DROP TABLE IF EXISTS `review`;
Executing (default): DROP TABLE IF EXISTS `user`;
Executing (default): DROP TABLE IF EXISTS `restaurant`;
Executing (default): CREATE TABLE IF NOT EXISTS `restaurant` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `food_type` VARCHAR(255) NOT NULL, `pet_allowed` VARCHAR(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `restaurant`
Executing (default): DROP TABLE IF EXISTS `user`;
Executing (default): CREATE TABLE IF NOT EXISTS `user` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255) NOT NULL, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `user`
Executing (default): DROP TABLE IF EXISTS `review`;
Executing (default): CREATE TABLE IF NOT EXISTS `review` (`id` INTEGER NOT NULL auto_increment , `comment` TEXT, `date_created` DATETIME NOT NULL, `restaurant_id` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`restaurant_id`) REFERENCES `restaurant` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `review`
Executing (default): INSERT INTO `restaurant` (`id`,`name`,`description`,`food_type`,`pet_allowed`) VALUES (DEFAULT,?,?,?,?);
Executing (default): INSERT INTO `restaurant` (`id`,`name`,`description`,`food_type`,`pet_allowed`) VALUES (DEFAULT,?,?,?,?);
Executing (default): INSERT INTO `restaurant` (`id`,`name`,`description`,`food_type`,`pet_allowed`) VALUES (DEFAULT,?,?,?,?);
Executing (default): INSERT INTO `restaurant` (`id`,`name`,`description`,`food_type`,`pet_allowed`) VALUES (DEFAULT,?,?,?,?);
Executing (default): INSERT INTO `review` (`id`,`comment`,`date_created`,`restaurant_id`) VALUES (DEFAULT,?,?,?);
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/sequelize/lib/sequelize.js:314:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
    at async Review.save (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/sequelize/lib/model.js:2432:35)
    at async review.create (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/sequelize/lib/model.js:1344:12)
    at async seedDatabase (/Users/rwhit/Develop/ucb_bootcamp/project-2/seeds/seed.js:16:5) {
  name: 'SequelizeForeignKeyConstraintError',
  parent: Error: Cannot add or update a child row: a foreign key constraint fails (`restreview_db`.`review`, CONSTRAINT `review_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Execute.execute (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`restreview_db`.`review`, CONSTRAINT `review_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'INSERT INTO `review` (`id`,`comment`,`date_created`,`restaurant_id`) VALUES (DEFAULT,?,?,?);',
    parameters: [
      'The service was spot on, the waitress was great at explaining everything we were eating. ',
      '2022-09-26 01:50:20',
      2
    ]
  },
  original: Error: Cannot add or update a child row: a foreign key constraint fails (`restreview_db`.`review`, CONSTRAINT `review_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
      at Packet.asError (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Execute.execute (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/rwhit/Develop/ucb_bootcamp/project-2/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`restreview_db`.`review`, CONSTRAINT `review_ibfk_1` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)',
    sql: 'INSERT INTO `review` (`id`,`comment`,`date_created`,`restaurant_id`) VALUES (DEFAULT,?,?,?);',
    parameters: [
      'The service was spot on, the waitress was great at explaining everything we were eating. ',
      '2022-09-26 01:50:20',
      2
    ]
  },
  sql: 'INSERT INTO `review` (`id`,`comment`,`date_created`,`restaurant_id`) VALUES (DEFAULT,?,?,?);',
  parameters: [
    'The service was spot on, the waitress was great at explaining everything we were eating. ',
    '2022-09-26 01:50:20',
    2
  ],
  table: 'user',
  fields: [ 'id' ],
  value: undefined,
  index: 'review_ibfk_1',
  reltype: 'child'
}

Node.js v18.9.0
```

**Comment by ryan-whit** [comment]
Closed by #37.
